// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jsmfybxzykccjzafydkd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpzbWZ5Ynh6eWtjY2p6YWZ5ZGtkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg4OTA2OTYsImV4cCI6MjA3NDQ2NjY5Nn0.J8IAf_-ZWaErR0zjQtPEWfgFwm6U6et5z0Jl29ufLBU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});